uploads = []
generated = []

[[outputs]]
id = "fAc_RPo2_LwZpFCEDRR75"
uri = "file://scripts/postman/Branch-Migration-API.postman_collection.json"
type = "unspecified"
title = "Branch Migration API — Postman Collection"
